services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    command: --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - .env
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  app:
    build: ./flask
    container_name: flask_app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mysql
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  mongodb-data:
